image: Visual Studio 2019

environment:
  UmbPackKey:
    secure: Y/76f3rkb4wyNyny/hPXqxyFyn1ttDUgCyKHKTEn8qUBP/GtRdZqD+bG5u4nhlccD1700FfRJsZgUp1qjRWKx8H4PsXmaRKklwJJ2fs4P+k=
  
cache:
  - '%APPDATA%\npm-cache'
  - '%LocalAppData%\NuGet\v3-cache'

install:
  - ps: Install-Product node 12
  - cmd: dotnet tool install --global Umbraco.Tools.Packages

platform: Any CPU
configuration: Release

before_build:
  - nuget restore

build:
  parallel: true

test: off

artifacts:
  - path: 'NestingContently.Umbraco\bin\$(configuration)\*.nupkg'
    name: NuGet_NestingContently
  - path: 'NestingContently.Umbraco\bin\$(configuration)\*.zip'
    name: UmbPack_NestingContently

  - path: 'NestingContently.Umbraco.ValueConverters\bin\$(configuration)\*.nupkg'
    name: NuGet_NestingContently_ValueConverters
  - path: 'NestingContently.Umbraco.ValueConverters\bin\$(configuration)\*.snupkg'
    name: NuGetSymbols_NestingContently_ValueConverters
  - path: 'NestingContently.Umbraco.ValueConverters\bin\$(configuration)\*.zip'
    name: UmbPack_NestingContently_ValueConverters

deploy:
  - provider: NuGet
    api_key:
      secure: 3rS8SSsTr0VHNAkG7ayAvic+yEedX8IIKq9QwaNrtLYDzgpyZJjY1mLuBYDZF0Qj
    on:
        APPVEYOR_REPO_TAG: true

  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    description: ''
    auth_token:
        secure: Otbl8p8qCwciDqJgSWCyN0Arfs5XS1CwiHcK+r0F6uz9Rxt4gzBFvlc3cjPV3NxR
    on:
        APPVEYOR_REPO_TAG: true

after_deploy:
  - ps: |
      # Only run this script on tagged builds
      if ($env:APPVEYOR_REPO_TAG -ne "true") { return }

      # Push NestingContently Umbraco package
      $path = $artifacts["UmbPack_NestingContently"].path
      if ($path) {
        umbpack push $path -c false -k $env:UmbPackKey -a Nesting_Contently_1.*
        
        # Also push NestingContently ValueConverters Umbraco package
        $path = $artifacts["UmbPack_NestingContently_ValueConverters"].path
        if ($path) {
          umbpack push $path -c false -k $env:UmbPackKey -a Nesting_Contently_Value_Converters_1.*
        }
      }
